# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 21:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(choices=[(b'IC', b'Introductory Clause'), (b'OC', b'Operative Clause')], default=b'IC', max_length=2)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClauseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.Clause')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'AFCO', b'Constitutional Affairs'), (b'AFET', b'Foreign Affairs'), (b'AGRI', b'Agriculture and Rural Development'), (b'BUDG', b'Budgets'), (b'CULT', b'Culture and Education'), (b'DEVE', b'Development'), (b'DROI', b'Human Rights'), (b'ECON', b'Economic and Monetary Affairs'), (b'EMPL', b'Employment and Social Affairs'), (b'ENVI', b'Environment, Public Health and Food Safety'), (b'FEMM', b"Women's Rights and Gender Equality"), (b'IMCO', b'Internal Market and Consumer Protection'), (b'INTA', b'International Trade'), (b'ITRE', b'Industry, Research and Energy'), (b'JURI', b'Legal Affairs'), (b'LIBE', b'Civil Liberties, Justice and Home Affairs'), (b'PECH', b'Fisheries'), (b'REGI', b'Regional Development'), (b'SEDE', b'Security and Defence'), (b'SPACE', b'Space'), (b'TRAN', b'Transport and Tourism')], default=b'AFCO', max_length=5)),
                ('number', models.CharField(blank=True, choices=[(b'', b''), (b'I', b'I'), (b'II', b'II'), (b'III', b'III'), (b'IV', b'IV')], default=b'', max_length=3, null=True)),
                ('topic', models.TextField()),
                ('submitted_by', models.TextField()),
                ('position', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FactSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.Committee')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('ga_start_date', models.DateField(verbose_name=b'start date')),
                ('ga_end_date', models.DateField(verbose_name=b'end date')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL)),
                ('resolution_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubClause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.Clause')),
            ],
        ),
        migrations.CreateModel(
            name='SubClauseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('subclause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.SubClause')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.PositiveSmallIntegerField()),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.Committee')),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.Session'),
        ),
        migrations.AddField(
            model_name='clause',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.Committee'),
        ),
    ]
