# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='res.Subtopic'),
        ),
    ]
