# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0002_clause_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(choices=[(b'AFCO', b'Constitutional Affairs'), (b'AFET', b'Foreign Affairs'), (b'AGRI', b'Agriculture and Rural Development'), (b'BUDG', b'Budgets'), (b'CULT', b'Culture and Education'), (b'DEVE', b'Development'), (b'DROI', b'Human Rights'), (b'ECON', b'Economic and Monetary Affairs'), (b'EMPL', b'Employment and Social Affairs'), (b'ENVI', b'Environment, Public Health and Food Safety'), (b'FEMM', b'Womens Rights and Gender Equality'), (b'IMCO', b'Internal Market and Consumer Protection'), (b'INTA', b'International Trade'), (b'ITRE', b'Industry, Research and Energy'), (b'JURI', b'Legal Affairs'), (b'LIBE', b'Civil Liberties, Justice and Home Affairs'), (b'PECH', b'Fisheries'), (b'REGI', b'Regional Development'), (b'SEDE', b'Security and Defence'), (b'SPACE', b'Space'), (b'TRAN', b'Transport and Tourism')], default=b'AFCO', max_length=5),
        ),
    ]
