# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_auto_20160516_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclause',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
