# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0004_subclause_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clause',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subclause',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
