# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0005_auto_20160516_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
